# Generated by Django 3.2.7 on 2022-03-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_programms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programms',
            name='set',
            field=models.CharField(choices=[('открыт', 'открыт'), ('закрыт', 'закрыт')], default='закрыт', max_length=50, verbose_name='Набор'),
        ),
    ]
