# Generated by Django 3.2.7 on 2022-05-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_consulting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulting',
            name='answer',
            field=models.BooleanField(default=False, verbose_name='Ответ'),
        ),
    ]
